core/urls.py
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path('', views.index, name='index'),
    path('new-post', views.new_post, name='new-post'),
    path('new-comment/<int:post_id>/', views.new_comment, name='new-comment'),
    path('like/<int:post_id>/', views.like, name='like'),
    path('dislike/<int:post_id>/', views.dislike, name='dislike'),
    path('un/<int:post_id>/', views.superUn, name='superUn'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
]

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('core.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.log, name='login'),
    path('myprofile/', views.my_profile, name='myprofile'),
    path('logout/', views.out, name='logout'),
    path('profile/<str:profile_username>/', views.profile, name='profile'),
    path('new-request/<str:profile_username>/', views.friend_request, name='friend_request'),
    path('delete-request/<str:profile_username>/', views.delete_request, name='delete_request'),
    path('accept/<str:profile_username>/', views.accept, name='accept'),
    path('delete/<str:profile_username>/', views.delete, name='delete'),
    path('myfriends/', views.myfriends, name='myfriends'),
]

core/models.py
from django.db import models
from users.models import User

class Post(models.Model):
    text = models.TextField(max_length=500, null=False, blank=False)
    rating = models.IntegerField(default=0)
    # likes = models.IntegerField(default=0)
    # dislikes = models.IntegerField(default=0)
    image = models.ImageField(upload_to='posts/', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    liked_by = models.ManyToManyField(User, related_name='liked_posts')
    disliked_by = models.ManyToManyField(User, related_name='disliked_posts')
    date = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    text = models.TextField(max_length=300, null=True, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments')
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')

core/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from django.db import IntegrityError


def index(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'core/index.html', context=context)

def new_comment(request, post_id):
    if request.method == 'POST':
            post = Post.objects.get(id=post_id)
            text = request.POST.get('comment')
            author = request.user
            comment = Comment.objects.create(post=post, text=text, author=author)
    return redirect('core:index')

def delete(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(id=post_id).delete()
    return redirect('core:index')

def like(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(id=post_id)
        user = request.user
        if user in post.disliked_by.all():
            post.rating += 2
            post.disliked_by.remove(user)
            post.liked_by.add(user)
        else:
            post.rating += 1
            post.liked_by.add(user)
        post.save()
    return redirect('core:index')

def dislike(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(id=post_id)
        user = request.user
        if user in post.liked_by.all():
            post.rating -= 2
            post.liked_by.remove(user)
            post.disliked_by.add(user)
        else:
            post.rating -= 1
            post.disliked_by.add(user)
        post.save()
    return redirect('core:index')

def superUn(request, post_id):
    if request.method == 'POST':
        user = request.user
        post = Post.objects.get(id=post_id)
        if user in post.disliked_by.all():
            post.rating += 1
            post.disliked_by.remove(user)
        if user in post.liked_by.all():
            post.rating -= 1
            post.liked_by.remove(user)
        post.save()
    return redirect('core:index')


def new_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            text = request.POST.get('text')
            image = request.FILES.get('image')
            user = request.user
            try:
                post = Post.objects.create(text=text, image=image, author=user)
            except IntegrityError:
                error = 'Creation failed'
                return render(request, 'core/new-post.html', {'error': error})
        return render(request, 'core/new-post.html')
    else:
        return redirect('core:index')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}core:base.html{% endblock title %}</title>
    <style>
        {% block css %}{% endblock css %}
        {% block header-css %}
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            background-color: #333;
            color: white;
        }
        .header-links {
            display: flex;
        }
        .header-links a {
            margin-right: 20px;
            color: white;
            text-decoration: none;
        }
        .avatar-container {
            display: flex;
            align-items: center;
        }
        .avatar-container > span {
            margin-right: 10px;
            margin-left: 10px;
        }
        .avatar {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            margin-right: 10px;
        }
        .username {
            color: white;
            margin-right: 10px;
        }
        .logout-btn {
            background-color: red;
            color: white;
            border: none;
            padding: 5px 10px;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;
        }
        {% endblock header-css %}
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% block header %}
    <div class="header">
        <div class="header-links">
            <a href="{% url "core:index" %}">Index</a>
            {% if user.is_authenticated %}
            <a href="{% url "core:new-post" %}">New Post</a>
            <a href="{% url "users:myfriends" %}">Friends</a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="avatar-container">
            <form action="{% url "users:logout" %}">
                {% csrf_token %}
                <button class="logout-btn">Logout</button>
            </form>
            {% if user.avatar %}
            <a href="{% url "users:myprofile" %}"><img src="{{ user.avatar.url }}" alt="img error" class="avatar"></a>
            {% endif %}
            <a href="{% url "users:myprofile" %}" class="username"><span>@{{ user.username }}</span></a>
        </div>
        {% else %}
        <div class="avatar-container">
            <a href="{% url "users:login" %}">Sing in</a>
            <span> or </span>
            <a href="{% url "users:registration" %}">Create account</a>
        </div>
        {% endif %}
    </div>
    {% endblock header %}
    
    {% block content %}
    
    {% endblock content %}
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Index{% endblock title %}

{% block css %}
.post-container {
    width: 40%;
    margin: 20px auto;
    padding: 10px;
    border: 1px solid #333;
    border-radius: 5px;
}
hr {
    border: none;
    border-top: 1px solid #333;
}
.post-header {
    display: flex;
    align-items: center;
    margin-bottom: 10px;
}

.post-author-image {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    margin-right: 10px;
}

.user-info {
    flex: 1;
}

.username {
    font-weight: bold;
}

.post-date {
    color: #333;
}

.author-comment {
    margin-bottom: 10px;
}

.post-image {
    margin-bottom: 10px;
}

.main-image {
    width: 100%;
    height: auto;
    border-radius: 2%;
}

.comments {
    margin-bottom: 10px;
}

.comment {
    margin-bottom: 5px;
}
.actions {
    display: flex;
    justify-content: center;
    margin-top: 10px;
}

.like-btn {
    margin: 0 5px;
    padding: 5px 10px;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #0faae4;
    cursor: pointer;
}
 .dislike-btn {
    margin: 0 5px;
    padding: 5px 10px;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #ff0000;
    cursor: pointer;
 }

.like-btn:hover {
    background-color: #0e99cd;
}
.dislike-btn:hover {
    background-color: #db0202;
}
.not {
    text-align: center;
}
.del-btn {
    margin: 0 5px;
    padding: 5px 10px;
    background-color: red;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #333;
    cursor: pointer;
}
.del-btn:hover {
    background-color: #444445;
}
{% endblock css %}


{% block content %}
{% comment %} {% if not user.is_authenticated %}
<div class="post-container not">
<h1>! WARNING !</h1>
<h2>To access the full functionality of the site, please:</h2>
<h2><a href="{% url "users:registration" %}">create</a> or <a href="{% url "users:login" %}">sign in</a> into your account!</h2>
</div>
{% endif %} {% endcomment %}
{% if posts %}
    {% for post in posts %}
        <div class="post-container">
            <div class="post-header">
                {% if user.id == post.author.id %}
                    {% if post.author.avatar %}
                    <a href="{% url "users:myprofile"%}"><img src="{{ post.author.avatar.url }}" alt="Avatar" class="post-author-image"></a>
                    {% endif %}
                    <div class="user-info">
                        <span class="post-username">@<a href="{% url "users:myprofile" %}">{{ post.author.username }}</a></span>
                        <span class="post-date">{{ post.date }} |</span>
                        <span class="post-rating">Rating: {{ post.rating }}</span>
                        <hr>
                    </div>
                    {% else %}
                        <a href="{% url "users:profile" post.author.username %}"><img src="{{ post.author.avatar.url }}" alt="Avatar" class="post-author-image"></a>
                        <div class="user-info">
                            <span class="post-username">@<a href="{% url "users:profile" post.author.username %}">{{ post.author.username }}</a></span>
                            <span class="post-date">{{ post.date }} |</span>
                            <span class="post-rating">Rating: {{ post.rating }}</span>
                            <hr>
                        </div>
                {% endif %}
            </div>
            <div class="author-comment">
                <p>{{ post.text }}</p>
            </div>
            {% if post.image %}
                <div class="post-image">
                    <img src="{{ post.image.url }}" alt="Post Image" class="main-image">
                </div>
            {% endif %}
            {% if user.is_authenticated %}
                <div class="actions">
                    {% if user.id == post.author.id %}
                        <form action="{% url "core:delete" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="del-btn">Delete post</button>
                        </form>
                    {% else %}
                        {% if user not in post.liked_by.all and user not in post.disliked_by.all %}
                        <form action="{% url "core:like" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="like-btn">Like</button>
                        </form>
                        <form action="{% url "core:dislike" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="dislike-btn">Dislike</button>
                        </form>
                        {% endif %}
                    {% endif %}
                    {% if user in post.liked_by.all %}
                    <form action="{% url "core:superUn" post.id %}" method='post'>
                    {% csrf_token %}
                    <button class="like-btn">Unlike</button>
                    </form>
                    <form action="{% url "core:dislike" post.id %}" method='post'>
                        {% csrf_token %}
                        <button class="dislike-btn">Dislike</button>
                    </form>
                    {% endif %}
                    {% if user in post.disliked_by.all %}
                    <form action="{% url "core:like" post.id %}" method='post'>
                        {% csrf_token %}
                        <button class="like-btn">Like</button>
                    </form>
                    <form action="{% url "core:superUn" post.id %}" method='post'>
                        {% csrf_token %}
                        <button class="dislike-btn">Undislike</button>
                    </form>
                    {% endif %}
                </div>
            {% endif %}
            {% if post.post_comments %}
                {% for comment in post.post_comments.all %}
                <div class="comments">
                    <div class="comment">
                        <hr>
                        {% if comment.author.id == user.id %}
                        <span>@<a href="{% url "users:myprofile" %}">{{ comment.author.username }}</a></span>
                        {% else %}
                        <span>@<a href="{% url "users:profile" comment.author.username %}">{{ comment.author.username }}</a></span>
                        {% endif %}
                        <p>{{ comment.text }}</p>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            {% if user.is_authenticated %}
            <hr>
            <div class="new-comment">
                <form action="{% url 'core:new-comment' post.id %}" method="post">
                    {% csrf_token %}
                    <input type="text" id="comment" name="comment" placeholder="Leave a comment">
                    <button type="submit">Submit</button>
                </form>
            </div>
            {% endif %}
        </div>
    {% endfor %}
{% else %}
    {% if user.is_authenticated %}
    <div class="post-container not">
    <h1>! NO POSTS YET !</h1>
    <h2>You can create new posts <a href="{% url "core:new-post" %}">here</a>.</h2>
    </div>
    {% else %}
    <div class="post-container not">
    <h1>! NO POSTS YET !</h1>
    <h2>To create posts, please <a href="{% url "users:registration" %}">register</a> or <a href="{% url "users:login" %}">sign in</a>.</h2>
    <h3>After that you will be able to create new posts <a href="{% url "core:new-post" %}">here</a>.</h3>
    </div>
    {% endif %}
{% endif %}
{% endblock content %}

core/templates/core/new-post.html
{% extends "core/base.html" %}

{% block title %}Create new post{% endblock title %}

{% block css %}
.post-container{
    width: 40%;
    align-items: center;
    margin: 0 auto;
}
.new-post-form {
    margin-top: 20px;
}

.new-post-form input[type="text"],
.new-post-form input[type="file"] {
    width: 100%;
    padding: 10px;
    margin-bottom: 10px;
}

.new-post-form button {
    padding: 10px;
    background-color: #0faae4;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

.new-post-form button:hover {
    background-color: #0e99cd;
}
{% endblock css %}

{% block content %}
<div class="post-container new-post-form">
    <h2>Create New Post</h2>
    <p>{{ error }}</p>
    <form action="{% url "core:new-post" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="text" id="text" placeholder="Enter post text" required>
        <input type="file" name="image" id="image">
        <button type="submit">Create Post</button>
    </form>
</div>
{% endblock content %}