core/urls.py
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path('', views.index, name='index'),
    path('new-post', views.new_post, name='new-post'),
    path('new-comment/<int:post_id>/', views.new_comment, name='new-comment'),
    path('like/<int:post_id>/', views.like, name='like'),
    path('dislike/<int:post_id>/', views.dislike, name='dislike'),
    path('un/<int:post_id>/', views.superUn, name='superUn'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
]

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('core.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.log, name='login'),
    path('myprofile/', views.my_profile, name='myprofile'),
    path('logout/', views.out, name='logout'),
    path('profile/<str:profile_username>/', views.profile, name='profile'),
    path('new-request/<str:profile_username>/', views.friend_request, name='friend_request'),
    path('delete-request/<str:profile_username>/', views.delete_request, name='delete_request'),
    path('accept/<str:profile_username>/', views.accept, name='accept'),
    path('delete/<str:profile_username>/', views.delete, name='delete'),
    path('myfriends/', views.myfriends, name='myfriends'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    friends = models.ManyToManyField('self', symmetrical=False, blank=True)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(User, related_name='request_sent', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='request_received', on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    

users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.models import User
from .models import User, FriendRequest
from django.contrib.auth import authenticate, login, logout

def delete_request(request, profile_username):
    if request.method == 'POST':
        user = request.user
        friend = User.objects.filter(username=profile_username).first()
        request = FriendRequest.objects.filter(from_user=user.id, to_user=friend.id)
        request.delete()
        return redirect('users:profile', profile_username=profile_username)

def friend_request(request, profile_username):
    if request.method == 'POST':
        user = request.user
        profile = User.objects.get(username=profile_username)
        request = FriendRequest.objects.create(from_user=user, to_user=profile)
        request.save()
        if request is not None:
            request.save()
            return redirect('users:profile', profile_username=profile_username)
        else:
            # message = "Request's error!"
            return render(request, 'users/myfriends.html')
        

def accept(request, profile_username):
    if request.method == 'POST':
        from_user = User.objects.get(username = profile_username)
        to_user = request.user
        friend_request = FriendRequest.objects.filter(from_user=from_user.id, to_user=to_user.id).first()
        if friend_request:
            friend_request.delete()
            from_user.friends.add(to_user)
            to_user.friends.add(from_user)
        return redirect('users:myfriends')

def delete(request, profile_username):
    if request.method == 'POST':
        user = request.user
        friend = User.objects.filter(username=profile_username).first()
        user.friends.remove(friend)
        friend.friends.remove(user)
        return redirect('users:myfriends')

def myfriends(request):
    user = request.user
    context = {
        'friend_requests': FriendRequest.objects.filter(to_user=user.id),
    }
    return render(request, 'users/myfriends.html', context=context)

def profile(request, profile_username):
    user = request.user
    context = {
    'profile': User.objects.get(username=profile_username),
    'requests': FriendRequest.objects.all(),
    }
    return render(request, 'users/profile.html', context=context)

def registration(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        psw = request.POST.get('psw')
        psw_repeat = request.POST.get('psw_repeat')
        if psw == psw_repeat:
            user = User.objects.create_user(email=email, username=username, password=psw)
            if user is not None:
                login(request, user)
                return redirect('users:myprofile')
            else:
                message = "Registration's error!"
                return render(request, 'users/registration.html', {'message': message})
    else:
        if request.user.is_authenticated:
            message = "By filling this form you'll create new account!"
            return render(request, 'users/registration.html', {'message': message})
        return render(request, 'users/registration.html')

def log(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        psw = request.POST.get('psw')
        user = authenticate(request, username=username, password=psw)
        if user is not None:
            login(request, user)
            return redirect('users:myprofile')
        else:
            message = "Login's error!"
            return render(request, 'users/login.html', {'message': message}) 
    else:
        if request.user.is_authenticated:
            message = "By filling this form you'll log in in another account!"
            return render(request, 'users/login.html', {'message': message})
        return render(request, 'users/login.html')

def my_profile(request):
    user = request.user
    posts = user.posts
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('psw')
        first_name = request.POST.get('fn')
        last_name = request.POST.get('ln')
        avatar = request.FILES.get('avatar')

        if email:
            user.email = email
        if username:
            user.username = username
        if password:
            user.set_password(password)
        if first_name:
            user.first_name = first_name
        if last_name:
            user.last_name = last_name
        if avatar:
            user.avatar = avatar

        if any([email, username, password, first_name, last_name, avatar]):
            user.save()

        if password:
            login(request, user)

        return redirect('users:myprofile')

    return render(request, 'users/myprofile.html', {'user': user, 'posts': posts})

def out(request):
    logout(request)
    return redirect('users:login')

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}users:base.html{% endblock title %}</title>
    <style>
        {% block css %}
        {% endblock css %}
        {% block header-css %}
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            background-color: #333;
            color: white;
        }
        .header-links {
            display: flex;
        }
        .header-links a {
            margin-right: 20px;
            color: white;
            text-decoration: none;
        }
        .avatar-container {
            display: flex;
            align-items: center;
        }
        .avatar-container > span {
            margin-right: 10px;
            margin-left: 10px;
        }
        .avatar {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            margin-right: 10px;
        }
        .username {
            color: white;
            margin-right: 10px;
        }
        .logout-btn {
            background-color: red;
            color: white;
            border: none;
            padding: 5px 10px;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;
        }
        {% endblock header-css %}
    </style>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% block header %}
    <div class="header">
        <div class="header-links">
            <a href="{% url "core:index" %}">Index</a>
            {% if user.is_authenticated %}
            <a href="{% url "core:new-post" %}">New Post</a>
            <a href="{% url "users:myfriends" %}">Friends</a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="avatar-container">
            <form action="{% url "users:logout" %}">
                {% csrf_token %}
                <button class="logout-btn">Logout</button>
            </form>
            {% if user.avatar %}
            <a href="{% url "users:myprofile" %}"><img src="{{ user.avatar.url }}" alt="img error" class="avatar"></a>
            {% endif %}
            <a href="{% url "users:myprofile" %}" class="username"><span>@{{ user.username }}</span></a>
        </div>
        {% else %}
        <div class="avatar-container">
            <a href="{% url "users:login" %}">Sing in</a>
            <span> or </span>
            <a href="{% url "users:registration" %}">Create account</a>
        </div>
        {% endif %}
    </div>
    {% endblock header %}
    {% block content %}{% endblock content %}
</body>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}

{% block title %}Login{% endblock title %}
{% block css %}
.log-form {
    text-align: center;
}
{% endblock css %}


{% block content %}
<form action="{% url "users:login" %}" class="log-form" method='post'>
  {% csrf_token %}
    <div class="container">
      <h1>Login</h1>
      {% if message %}
      <p>{{ message }}</p>
      {% else %}
      <p>Fill this form to log into your account.</p>
      {% endif %}
      <hr>
      <label for="username"><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="username" id="username" required>
  
      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" id="psw" required>
      <hr>
      <button type="submit" class="logbtn">Login</button>
    </div>
  
    <div class="container signin">
      <p>Don't have an account? <a href="{% url "users:registration" %}">Create one!</a></p>
    </div>
  </form>
{% endblock content %}

users/templates/users/myprofile.html
{% extends "users/base.html" %}

{% block title %}Profile{% endblock title %}

{% block css %}
.container {
    text-align: center;
}
.profile-avatar {
    width: 150px;
    height: 150px;
    border-radius: 50%;
}
.post-container {
    width: 40%;
    margin: 20px auto;
    padding: 10px;
    border: 1px solid #333;
    border-radius: 5px;
}
hr {
    border: none;
    border-top: 1px solid #333;
}
.post-header {
    display: flex;
    align-items: center;
    margin-bottom: 10px;
}

.post-author-image {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    margin-right: 10px;
}

.user-info {
    flex: 1;
}

.username {
    font-weight: bold;
}

.post-date {
    color: #333;
}

.author-comment {
    margin-bottom: 10px;
}

.post-image {
    margin-bottom: 10px;
}

.main-image {
    width: 100%;
    height: auto;
    border-radius: 2%;
}

.comments {
    margin-bottom: 10px;
}

.comment {
    margin-bottom: 5px;
}
.actions {
    display: flex;
    justify-content: center;
    margin-top: 10px;
}

.like-btn {
    margin: 0 5px;
    padding: 5px 10px;
    background-color: red;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #0faae4;
    cursor: pointer;
}
 .dislike-btn {
    margin: 0 5px;
    padding: 5px 10px;
    background-color: red;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #ff0000;
    cursor: pointer;
 }

.like-btn:hover {
    background-color: #0e99cd;
}
.dislike-btn:hover {
    background-color: #db0202;
}
.not {
    text-align: center;
}
.del-btn {
    margin: 0 5px;
    padding: 5px 10px;
    background-color: red;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #333;
    cursor: pointer;
}
.del-btn:hover {
    background-color: #444445;
}
{% endblock css %}

{% block content %}
{% comment %} <form action="{% url 'users:logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Logout</button>
</form> {% endcomment %}
<div class="container">
{% if user.is_authenticated %}
    <p>Hello, @{{ user.username }}</p>
        {% if user.avatar %}
        <img src="{{ user.avatar.url }}" alt="img error" class="profile-avatar">
        {% endif %}
        <p>Account created at: {{ user.date_joined }}</p>
        <p>Last login at: {{ user.last_login }}</p>
        <form action="{% url "users:logout" %}">
        {% csrf_token %}
        <button class="logout">Logout</button>
        </form>
        <form action="{% url "users:myprofile" %}" method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <hr>
            <hr>
            <label for="email"><b>Email</b></label>
            <input type="email" placeholder="{{ user.email }}" name="email" id="email">
            <label for="username"><b>Username</b></label>
            <input type="text" placeholder="@{{ user.username }}" name="username" id="username">
            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter new password" name="psw" id="psw">
            <hr>
            <label for="fn"><b>First name</b></label>
            <input type="text" placeholder="{{ user.first_name }}" name="fn" id="fn">
            <label for="ln"><b>Last name</b></label>
            <input type="text" placeholder="{{ user.last_name }}" name="ln" id="ln">
            <hr>
            <label for="avatar"><b>Avatar</b></label>
            <input type="file" name="avatar" id="avatar">
            <hr>
            <hr>
            <button type="submit" class="registerbtn">Save</button>
        </form>
    </div>
    <hr>
    {% if user.posts.all %}
    <div class="container">
        <p>My posts</p>
    </div>
        {% for post in user.posts.all %}
            <div class="post-container">
                <div class="post-header">
                    {% if user.id == post.author.id %}
                        {% if post.author.avatar %}
                        <a href="{% url "users:myprofile"%}"><img src="{{ post.author.avatar.url }}" alt="Avatar" class="post-author-image"></a>
                        {% endif %}
                        <div class="user-info">
                            <span class="post-username">@<a href="{% url "users:myprofile" %}">{{ post.author.username }}</a></span>
                            <span class="post-date">{{ post.date }} |</span>
                            <span class="post-rating">Rating: {{ post.rating }}</span>
                            <hr>
                        </div>
                        {% else %}
                            <a href="{% url "users:profile" post.author.username %}"><img src="{{ post.author.avatar.url }}" alt="Avatar" class="post-author-image"></a>
                            <div class="user-info">
                                <span class="post-username">@<a href="{% url "users:profile" post.author.username %}">{{ post.author.username }}</a></span>
                                <span class="post-date">{{ post.date }} |</span>
                                <span class="post-rating">Rating: {{ post.rating }}</span>
                                <hr>
                            </div>
                    {% endif %}
                </div>
                <div class="author-comment">
                    <p>{{ post.text }}</p>
                </div>
                {% if post.image %}
                    <div class="post-image">
                        <img src="{{ post.image.url }}" alt="Post Image" class="main-image">
                    </div>
                {% endif %}
                {% if user.is_authenticated %}
                    <div class="actions">
                        {% if user.id == post.author.id %}
                            <form action="{% url "core:delete" post.id %}" method='post'>
                                {% csrf_token %}
                                <button class="del-btn">Delete post</button>
                            </form>
                        {% else %}
                            {% if user not in post.liked_by.all and user not in post.disliked_by.all %}
                            <form action="{% url "core:like" post.id %}" method='post'>
                                {% csrf_token %}
                                <button class="like-btn">Like</button>
                            </form>
                            <form action="{% url "core:dislike" post.id %}" method='post'>
                                {% csrf_token %}
                                <button class="dislike-btn">Dislike</button>
                            </form>
                            {% endif %}
                        {% endif %}
                        {% if user in post.liked_by.all %}
                        <form action="{% url "core:superUn" post.id %}" method='post'>
                        {% csrf_token %}
                        <button class="like-btn">Unlike</button>
                        </form>
                        <form action="{% url "core:dislike" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="dislike-btn">Dislike</button>
                        </form>
                        {% endif %}
                        {% if user in post.disliked_by.all %}
                        <form action="{% url "core:like" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="like-btn">Like</button>
                        </form>
                        <form action="{% url "core:superUn" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="dislike-btn">Undislike</button>
                        </form>
                        {% endif %}
                    </div>
                {% endif %}
                {% if post.post_comments %}
                    {% for comment in post.post_comments.all %}
                    <div class="comments">
                        <div class="comment">
                            <hr>
                            {% if comment.author.id == user.id %}
                            <span>@<a href="{% url "users:myprofile" %}">{{ comment.author.username }}</a></span>
                            {% else %}
                            <span>@<a href="{% url "users:profile" comment.author.username %}">{{ comment.author.username }}</a></span>
                            {% endif %}
                            <p>{{ comment.text }}</p>
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
                {% if user.is_authenticated %}
                <hr>
                <div class="new-comment">
                    <form action="{% url 'core:new-comment' post.id %}" method="post">
                        {% csrf_token %}
                        <input type="text" id="comment" name="comment" placeholder="Leave a comment">
                        <button type="submit">Submit</button>
                    </form>
                </div>
                {% endif %}
            </div>
        {% endfor %}
    {% endif %}
{% else %}
<h1>You're not autheficated!</h1>
<hr>
<p>Already have an account? <a href="{% url "users:login" %}">Sign in.</a></p>
<p>Don't have an account? <a href="{% url "users:registration" %}">Create one!</a></p>
</div>
{% endif %}

{% endblock content %}

users/templates/users/profile.html
{% extends "users/base.html" %}

{% block title %}@{{ profile.username }}'s profile{% endblock title %}

{% block css %}
.container {
    text-align: center;
    margin-top: 10px;
}
.profile-avatar {
    width: 150px;
    height: 150px;
    border-radius: 50%;
    margin-bottom: 10px;
}
.post-container {
    width: 40%;
    margin: 20px auto;
    padding: 10px;
    border: 1px solid #333;
    border-radius: 5px;
}
hr {
    border: none;
    border-top: 1px solid #333;
}
.post-header {
    display: flex;
    align-items: center;
    margin-bottom: 10px;
}

.post-author-image {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    margin-right: 10px;
}

.user-info {
    flex: 1;
}

.username {
    font-weight: bold;
}

.post-date {
    color: #333;
}

.author-comment {
    margin-bottom: 10px;
}

.post-image {
    margin-bottom: 10px;
}

.main-image {
    width: 100%;
    height: auto;
    border-radius: 2%;
}

.comments {
    margin-bottom: 10px;
}

.comment {
    margin-bottom: 5px;
}
.actions {
    display: flex;
    justify-content: center;
    margin-top: 10px;
}

.like-btn {
    margin: 0 5px;
    padding: 5px 10px;
    background-color: red;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #0faae4;
    cursor: pointer;
}
 .dislike-btn {
    margin: 0 5px;
    padding: 5px 10px;
    background-color: red;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #ff0000;
    cursor: pointer;
 }

.like-btn:hover {
    background-color: #0e99cd;
}
.dislike-btn:hover {
    background-color: #db0202;
}
.not {
    text-align: center;
}
.del-btn {
    margin: 0 5px;
    padding: 5px 10px;
    background-color: red;
    color: white;
    border: none;
    border-radius: 5px;
    background-color: #333;
    cursor: pointer;
}
.del-btn:hover {
    background-color: #444445;
}
.accept-btn {
    margin-top: 10px;
    border: none;
    padding: 5px 10px;
    background-color: red;
    color: white;
    background-color: #189159;
    cursor: pointer;
    border-radius: 5px;
}
.accept-btn:hover {
        background-color: #15794b;
}
{% endblock css %}

{% block content %}
<div class="container">
    {% if profile.avatar %}
    <img src="{{ profile.avatar.url }}" alt="img error" class="profile-avatar">
    {% endif %}
    <p>Date joined: {{ profile.date_joined }}</p>
    <p>Username: @{{ profile.username }}</p>
    <p>{{ profile.first_name }} {{ profile.last_name }}</p>
        {% if user.friends.all %}
        {% for friend in user.friends.all %}
            {% if friend.username == profile.username %}
            <form action="{% url "users:delete" friend.username %}" method='post'>
                {% csrf_token %}
                <button class="action-btn delete-btn">Delete from friends</button>
            </form>
            {% endif %}
        {% endfor %}
        {% else %}
        {% if requests %}
            {% for request in requests %}
                {% if request.to_user.id == profile.id and request.from_user.id == user.id %}
                    <form action="{% url "users:delete_request" profile.username %}" method='post'>
                    {% csrf_token %}
                    <button class="action-btn delete-btn">Delete my request</button>
                </form>
                {% endif %}
                {% if request.to_user.id == user.id and request.from_user.id == profile.id %}
                    <span>This user sent friend request to you</span>
                    <form action="{% url "users:accept" request.from_user.username %}" method='post'>
                    {% csrf_token %}
                    <button class="accept-btn">Accept</button>
                    </form>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% endif %}
        {% if not user.friends.all.exists and not requests %}
        <form action="{% url "users:friend_request" profile.username %}" method='post'>
            {% csrf_token %}
            <button class="like-btn">Send Friend Request</button>
        </form>
        {% endif %}
</div>
{% if profile.posts.all %}
<hr>
<div class="container">
    <p>@{{ profile.username }} posts</p>
</div>
    {% for post in profile.posts.all %}
        <div class="post-container">
            <div class="post-header">
                {% if user.id == post.author.id %}
                    {% if post.author.avatar.url %}
                    <a href="{% url "users:myprofile"%}"><img src="{{ post.author.avatar.url }}" alt="Avatar" class="post-author-image"></a>
                    {% endif %}
                    <div class="user-info">
                        <span class="post-username">@<a href="{% url "users:myprofile" %}">{{ post.author.username }}</a></span>
                        <span class="post-date">{{ post.date }} |</span>
                        <span class="post-rating">Rating: {{ post.rating }}</span>
                        <hr>
                    </div>
                    {% else %}
                        <a href="{% url "users:profile" post.author.username %}"><img src="{{ post.author.avatar.url }}" alt="Avatar" class="post-author-image"></a>
                        <div class="user-info">
                            <span class="post-username">@<a href="{% url "users:profile" post.author.username %}">{{ post.author.username }}</a></span>
                            <span class="post-date">{{ post.date }} |</span>
                            <span class="post-rating">Rating: {{ post.rating }}</span>
                            <hr>
                        </div>
                {% endif %}
            </div>
            <div class="author-comment">
                <p>{{ post.text }}</p>
            </div>
            {% if post.image %}
                <div class="post-image">
                    <img src="{{ post.image.url }}" alt="Post Image" class="main-image">
                </div>
            {% endif %}
            {% if user.is_authenticated %}
                <div class="actions">
                    {% if user.id == post.author.id %}
                        <form action="{% url "core:delete" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="del-btn">Delete post</button>
                        </form>
                    {% else %}
                        {% if user not in post.liked_by.all and user not in post.disliked_by.all %}
                        <form action="{% url "core:like" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="like-btn">Like</button>
                        </form>
                        <form action="{% url "core:dislike" post.id %}" method='post'>
                            {% csrf_token %}
                            <button class="dislike-btn">Dislike</button>
                        </form>
                        {% endif %}
                    {% endif %}
                    {% if user in post.liked_by.all %}
                    <form action="{% url "core:superUn" post.id %}" method='post'>
                    {% csrf_token %}
                    <button class="like-btn">Unlike</button>
                    </form>
                    <form action="{% url "core:dislike" post.id %}" method='post'>
                        {% csrf_token %}
                        <button class="dislike-btn">Dislike</button>
                    </form>
                    {% endif %}
                    {% if user in post.disliked_by.all %}
                    <form action="{% url "core:like" post.id %}" method='post'>
                        {% csrf_token %}
                        <button class="like-btn">Like</button>
                    </form>
                    <form action="{% url "core:superUn" post.id %}" method='post'>
                        {% csrf_token %}
                        <button class="dislike-btn">Undislike</button>
                    </form>
                    {% endif %}
                </div>
            {% endif %}
            {% if post.post_comments %}
                {% for comment in post.post_comments.all %}
                <div class="comments">
                    <div class="comment">
                        <hr>
                        {% if comment.author.id == user.id %}
                        <span>@<a href="{% url "users:myprofile" %}">{{ comment.author.username }}</a></span>
                        {% else %}
                        <span>@<a href="{% url "users:profile" comment.author.username %}">{{ comment.author.username }}</a></span>
                        {% endif %}
                        <p>{{ comment.text }}</p>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            {% if user.is_authenticated %}
            <hr>
            <div class="new-comment">
                <form action="{% url 'core:new-comment' post.id %}" method="post">
                    {% csrf_token %}
                    <input type="text" id="comment" name="comment" placeholder="Leave a comment">
                    <button type="submit">Submit</button>
                </form>
            </div>
            {% endif %}
        </div>
    {% endfor %}
{% endif %}

{% endblock content %}

users/templates/users/registration.html
{% extends "users/base.html" %}

{% block title %}Registration{% endblock title %}
{% block css %}
.reg-form {
    text-align: center;
}
{% endblock css %}


{% block content %}
<form action="{% url "users:registration" %}" class="reg-form" method='post'>
  {% csrf_token %}
    <div class="container">
      <h1>Registration</h1>
      {% if message %}
      <p>{{ message }}</p>
      {% else %}
      <p>Fill this form to create an account.</p>
      {% endif %}
      <hr>
      <label for="email"><b>Email</b></label>
      <input type="email" placeholder="Enter Email" name="email" id="email" required>

      <label for="username"><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="username" id="username" required>
  
      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" id="psw" required>
  
      <label for="psw_repeat"><b>Repeat Password</b></label>
      <input type="password" placeholder="Repeat Password" name="psw_repeat" id="psw_repeat" required>
      <hr>
      <button type="submit" class="registerbtn">Register</button>
    </div>
  
    <div class="container signin">
      <p>Already have an account? <a href="{% url "users:login" %}">Sign in.</a></p>
    </div>
  </form>
{% endblock content %}